kind: Service
apiVersion: v1
metadata:
  name: russia
  labels:
    app: russia
spec:
  selector:
    app: russia
  ports:
  - port: 9080
    name: http
  type: NodePort
---

kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: russia
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: russia
        version: v1
    spec:
      containers:
      - name: russia
        image: sdaschner/openliberty-russia-demo:1
        imagePullPolicy: Always
        ports:
        - containerPort: 9080
      restartPolicy: Always
---
